import {execFileSync} from 'node:child_process';
import {mkdtemp,mkdir,writeFile,readFile,chmod,copyFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';

// 只在 Mac 上构建，保留 Unix 执行权限；源码只来自已提交的 Git 内容。
if(process.platform!=='darwin')throw new Error('Mac 包须在 macOS runner 上构建。');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const run=(cmd,args)=>execFileSync(cmd,args,{cwd:root,encoding:'utf8',stdio:['ignore','pipe','inherit']}).trim();
const commit=run('git',['rev-parse','HEAD']);
const version=JSON.parse(await readFile(path.join(root,'package.json'),'utf8')).version;
if(!/^\d+\.\d+\.\d+$/.test(version))throw new Error('需要正式数字版本。');
const arch=process.arch;
if(!['arm64','x64'].includes(arch))throw new Error('不支持的 Mac 架构');
const name=`ielts-writing-studio-v${version}-macos-${arch}`;
const output=path.join(root,'release-artifacts');await mkdir(output,{recursive:true});
const build=await mkdtemp(path.join(os.tmpdir(),'jujin-mac-'));
const packageRoot=path.join(build,name);await mkdir(packageRoot);
const source=path.join(build,'source.tar');run('git',['archive','--format=tar',`--output=${source}`,commit]);
run('tar',['-xf',source,'-C',packageRoot]);
const tracked=run('git',['ls-tree','-r','--name-only',commit]).split('\n');
if(tracked.some(p=>/(^|\/)(?:tmp|output|release-artifacts|node_modules)\/|(^|\/)\.env(?:$|\.(?!example$))|\.log$|live-result\.json$|\.lnk$/.test(p)))throw new Error('来源包含禁止打包的文件');
const nodeVersion='v24.19.0';const nodeName=`node-${nodeVersion}-darwin-${arch}`;
const filename=`${nodeName}.tar.gz`;const base=`https://nodejs.org/dist/${nodeVersion}`;
async function download(url){const r=await fetch(url,{signal:AbortSignal.timeout(180000)});if(!r.ok)throw new Error(`下载失败 ${r.status}`);return Buffer.from(await r.arrayBuffer());}
const sums=await download(`${base}/SHASUMS256.txt`);
const line=sums.toString().split('\n').find(line=>line.trim().endsWith(` ${filename}`));
if(!line)throw new Error('官方校验清单缺少所需运行时');
const expected=line.split(/\s+/)[0];const archive=await download(`${base}/${filename}`);
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
if(hash(archive)!==expected)throw new Error('Node 官方 SHA256 不匹配');
const runtime=path.join(packageRoot,'runtime');await mkdir(runtime);
const runtimeArchive=path.join(build,filename);await writeFile(runtimeArchive,archive);
run('tar',['-xzf',runtimeArchive,'-C',runtime]);
await writeFile(path.join(runtime,'SHASUMS256.txt'),sums);
await copyFile(path.join(packageRoot,'scripts/macos/README.macos.zh-CN.md'),path.join(packageRoot,'Mac 使用说明.md'));
await chmod(path.join(packageRoot,'Start Writing Studio.command'),0o755);
const executable=path.join(runtime,nodeName,'bin/node');
if(run(executable,['-p','process.arch'])!==arch)throw new Error('打包架构错误');
await readFile(path.join(runtime,nodeName,'LICENSE'));
const manifest={version,sourceCommit:commit,platform:'macOS',arch,nodeVersion,nodeArchiveUrl:`${base}/${filename}`,nodeArchiveSHA256:expected,containsAIModel:false,containsCredentials:false,signed:false,notarized:false};
await writeFile(path.join(packageRoot,'MAC-MANIFEST.json'),JSON.stringify(manifest,null,2)+'\n');
const zip=path.join(output,`${name}.zip`);
run('/usr/bin/ditto',['-c','-k','--sequesterRsrc','--keepParent',packageRoot,zip]);
const digest=hash(await readFile(zip));
await writeFile(`${zip}.sha256`,`${digest}  ${path.basename(zip)}\n`);
await writeFile(path.join(output,`${name}.manifest.json`),JSON.stringify({...manifest,packageSHA256:digest},null,2)+'\n');
console.log(JSON.stringify({zip,packageRoot,arch,sourceCommit:commit}));
